remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

title: "Hermes Blog"
subtitle: "Salesforce Developer Blog"
name: "SFDC-Hermes"
description: "Apex, LWC, Integration"
url: "https://SFDC-Hermes.github.io"
baseurl: "/Lightning-Hermes"

author:
  name: "SFDC-Hermes"
  bio: "Salesforce Developer ⚡"

timezone: Asia/Seoul
locale: "ko-KR"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
